blank_issues_enabled: false
contact_links:
  - name: Questions, ideas and support
    url: https://github.com/harald666/vibez/discussions/categories/q-a
    about: Ask how-to questions, suggest ideas, share feedback or get general help with VibeZ.
