module.exports = {
  ru: {
    menu: ['Вставить','Копировать','Вырезать','Выбрать всё','Искать в Google','Искать в DuckDuckGo','Открыть VibeZ','Скриншот','Настройки','Проверить обновления','О VibeZ','Выход'],
    shot: ['Не удалось запустить инструмент скриншота.','Для этого экрана нет доступного источника.','Экраны не найдены.','Ошибка скриншота','VibeZ не удалось создать скриншот.','Выбрать область','Выделите область мышью · Esc = отмена'],
    dialog: ['Настольный клиент для Mistral Vibe','Копировать сведения о системе','Сообщить о проблеме','Закрыть','У вас уже установлена последняя версия VibeZ.','Не удалось проверить обновления.','Обновление VibeZ готово','VibeZ {version} готов к установке.','Перезапустить и обновить','Позже','Проверка обновлений доступна в установленных сборках VibeZ.','Это Flatpak-сборка.','Открыть Releases'],
    settings: ['Настройки VibeZ','Интеграция с рабочим столом','Глобальная клавиша скриншота','Клавиша скриншота','Показывать кнопку скриншота','Запускать при входе','Сворачивать в трей','Закрывать в трей','Экран','Аппаратное ускорение','Графический бэкенд','Масштаб','Язык VibeZ','Обновления и браузер','Автоматически проверять обновления','Устанавливать загруженные обновления при закрытии VibeZ','Открывать внешние ссылки в браузере по умолчанию','Данные браузера','Сбросить данные браузера','Сохранить настройки','Автоматически','Включено','Выключено','Система','Сохранение…','Сохранено.','Сохранено. Перезапустите VibeZ для применения всех изменений экрана/языка.','Сохранено, но эта глобальная клавиша уже используется.','Проверка обновлений…','Проверка обновлений запущена.','Удалить все данные браузера VibeZ? Вы выйдете из Mistral Vibe.','Очистка данных браузера…','Данные браузера очищены.','Данные браузера не были очищены.']
  },
  tr: {
    menu: ['Yapıştır','Kopyala','Kes','Tümünü seç','Google ile ara','DuckDuckGo ile ara','VibeZ’i aç','Ekran görüntüsü','Ayarlar','Güncellemeleri denetle','VibeZ hakkında','Çıkış'],
    shot: ['Ekran görüntüsü aracı başlatılamadı.','Bu ekran için kullanılabilir bir ekran kaynağı yok.','Ekran bulunamadı.','Ekran görüntüsü başarısız','VibeZ ekran görüntüsü oluşturamadı.','Ekran görüntüsü seç','Paylaşmak istediğiniz alanı sürükleyin · Esc = iptal'],
    dialog: ['Mistral Vibe için masaüstü istemcisi','Sistem bilgilerini kopyala','Sorun bildir','Kapat','Zaten VibeZ’in en son sürümünü kullanıyorsunuz.','Güncellemeler denetlenemedi.','VibeZ güncellemesi hazır','VibeZ {version} kurulmaya hazır.','Yeniden başlat ve güncelle','Daha sonra','Güncelleme denetimi kurulu VibeZ sürümlerinde kullanılabilir.','Bu Flatpak sürümüdür.','Releases’ı aç'],
    settings: ['VibeZ Ayarları','Masaüstü entegrasyonu','Genel ekran görüntüsü kısayolu','Ekran görüntüsü kısayolu','Ekran görüntüsü düğmesini göster','Oturum açınca başlat','Tepsiye küçült','Tepsiye kapat','Ekran','Donanım hızlandırma','Görüntü arka ucu','Yakınlaştırma','VibeZ dili','Güncellemeler ve tarayıcı','Güncellemeleri otomatik denetle','VibeZ kapanınca indirilen güncellemeleri kur','Harici bağlantıları varsayılan tarayıcıda aç','Tarayıcı verileri','Tarayıcı verilerini sıfırla','Ayarları kaydet','Otomatik','Etkin','Devre dışı','Sistem','Kaydediliyor…','Kaydedildi.','Kaydedildi. Tüm ekran/dil değişikliklerini uygulamak için VibeZ’i yeniden başlatın.','Kaydedildi, ancak bu genel kısayol zaten kullanımda.','Güncellemeler denetleniyor…','Güncelleme denetimi başlatıldı.','Tüm VibeZ tarayıcı verileri silinsin mi? Mistral Vibe oturumunuz kapanacaktır.','Tarayıcı verileri temizleniyor…','Tarayıcı verileri temizlendi.','Tarayıcı verileri temizlenmedi.']
  },
  pl: {
    menu: ['Wklej','Kopiuj','Wytnij','Zaznacz wszystko','Szukaj w Google','Szukaj w DuckDuckGo','Otwórz VibeZ','Zrzut ekranu','Ustawienia','Sprawdź aktualizacje','O VibeZ','Zakończ'],
    shot: ['Nie udało się uruchomić narzędzia zrzutu ekranu.','Brak dostępnego źródła ekranu dla tego monitora.','Nie znaleziono monitorów.','Błąd zrzutu ekranu','VibeZ nie mógł utworzyć zrzutu ekranu.','Wybierz zrzut ekranu','Przeciągnij po obszarze do udostępnienia · Esc = anuluj'],
    dialog: ['Klient desktopowy dla Mistral Vibe','Kopiuj informacje o systemie','Zgłoś problem','Zamknij','Masz już najnowszą wersję VibeZ.','Nie udało się sprawdzić aktualizacji.','Aktualizacja VibeZ gotowa','VibeZ {version} jest gotowy do instalacji.','Uruchom ponownie i zaktualizuj','Później','Sprawdzanie aktualizacji jest dostępne w zainstalowanych kompilacjach VibeZ.','To jest wersja Flatpak.','Otwórz Releases'],
    settings: ['Ustawienia VibeZ','Integracja z pulpitem','Globalny skrót zrzutu ekranu','Skrót zrzutu ekranu','Pokaż przycisk zrzutu ekranu','Uruchamiaj przy logowaniu','Minimalizuj do zasobnika','Zamykaj do zasobnika','Ekran','Przyspieszenie sprzętowe','Backend wyświetlania','Powiększenie','Język VibeZ','Aktualizacje i przeglądarka','Automatycznie sprawdzaj aktualizacje','Instaluj pobrane aktualizacje przy zamykaniu VibeZ','Otwieraj zewnętrzne linki w domyślnej przeglądarce','Dane przeglądarki','Resetuj dane przeglądarki','Zapisz ustawienia','Automatycznie','Włączone','Wyłączone','System','Zapisywanie…','Zapisano.','Zapisano. Uruchom VibeZ ponownie, aby zastosować wszystkie zmiany ekranu/języka.','Zapisano, ale ten globalny skrót jest już używany.','Sprawdzanie aktualizacji…','Rozpoczęto sprawdzanie aktualizacji.','Wyczyścić wszystkie dane przeglądarki VibeZ? Nastąpi wylogowanie z Mistral Vibe.','Czyszczenie danych…','Dane przeglądarki wyczyszczone.','Dane przeglądarki nie zostały wyczyszczone.']
  },
  uk: {
    menu: ['Вставити','Копіювати','Вирізати','Вибрати все','Шукати в Google','Шукати в DuckDuckGo','Відкрити VibeZ','Знімок екрана','Налаштування','Перевірити оновлення','Про VibeZ','Вийти'],
    shot: ['Не вдалося запустити інструмент знімка екрана.','Для цього дисплея немає доступного джерела екрана.','Дисплеї не знайдено.','Помилка знімка екрана','VibeZ не вдалося створити знімок екрана.','Вибрати знімок','Перетягніть по області для поширення · Esc = скасувати'],
    dialog: ['Настільний клієнт для Mistral Vibe','Копіювати інформацію про систему','Повідомити про проблему','Закрити','У вас уже найновіша версія VibeZ.','Не вдалося перевірити оновлення.','Оновлення VibeZ готове','VibeZ {version} готовий до встановлення.','Перезапустити й оновити','Пізніше','Перевірка оновлень доступна у встановлених збірках VibeZ.','Це Flatpak-версія.','Відкрити Releases'],
    settings: ['Налаштування VibeZ','Інтеграція з робочим столом','Глобальне скорочення знімка екрана','Скорочення знімка екрана','Показувати кнопку знімка','Запускати при вході','Згортати в трей','Закривати в трей','Дисплей','Апаратне прискорення','Бекенд відображення','Масштаб','Мова VibeZ','Оновлення та браузер','Автоматично перевіряти оновлення','Встановлювати завантажені оновлення при закритті VibeZ','Відкривати зовнішні посилання у типовому браузері','Дані браузера','Скинути дані браузера','Зберегти налаштування','Автоматично','Увімкнено','Вимкнено','Система','Збереження…','Збережено.','Збережено. Перезапустіть VibeZ, щоб застосувати всі зміни дисплея/мови.','Збережено, але це глобальне скорочення вже використовується.','Перевірка оновлень…','Перевірку оновлень розпочато.','Очистити всі дані браузера VibeZ? Ви вийдете з Mistral Vibe.','Очищення даних браузера…','Дані браузера очищено.','Дані браузера не очищено.']
  }
};
