module.exports = {
  fil: {
    menu: ['I-paste','Kopyahin','Gupitin','Piliin lahat','Maghanap sa Google','Maghanap sa DuckDuckGo','Buksan ang VibeZ','Screenshot','Mga setting','Tingnan ang updates','Tungkol sa VibeZ','Lumabas'],
    shot: ['Hindi masimulan ang screenshot tool.','Walang screen source para sa display na ito.','Walang nakitang display.','Nabigo ang screenshot','Hindi makagawa ng screenshot ang VibeZ.','Pumili ng screenshot','I-drag sa bahaging gusto mong ibahagi · Esc = kanselahin'],
    dialog: ['Desktop client para sa Mistral Vibe','Kopyahin ang impormasyon ng system','Mag-report ng problema','Isara','Nasa pinakabagong bersyon na ng VibeZ.','Hindi matingnan ang updates.','Handa na ang VibeZ update','Handa nang i-install ang VibeZ {version}.','I-restart at i-update','Mamaya','Available ang update checking sa naka-install na VibeZ builds.','Ito ang Flatpak build.','Buksan ang Releases'],
    settings: ['Mga setting ng VibeZ','Desktop integration','Global screenshot shortcut','Screenshot shortcut','Ipakita ang Screenshot button','Simulan sa login','I-minimize sa tray','Isara sa tray','Display','Hardware acceleration','Display backend','Zoom','Wika ng VibeZ','Updates at browser','Awtomatikong tingnan ang updates','I-install ang na-download na updates kapag isinara ang VibeZ','Buksan ang external links sa default browser','Browser data','I-reset ang browser data','I-save ang settings','Awtomatiko','Naka-enable','Naka-disable','System','Sine-save…','Nai-save.','Nai-save. I-restart ang VibeZ para mailapat ang lahat ng display/wika changes.','Nai-save, pero ginagamit na ang global shortcut na iyon.','Tinitingnan ang updates…','Nagsimula ang update check.','Burahin lahat ng VibeZ browser data? Masa-sign out ka sa Mistral Vibe.','Binubura ang browser data…','Nabura ang browser data.','Hindi nabura ang browser data.']
  },
  sw: {
    menu: ['Bandika','Nakili','Kata','Chagua yote','Tafuta kwa Google','Tafuta kwa DuckDuckGo','Fungua VibeZ','Picha ya skrini','Mipangilio','Angalia masasisho','Kuhusu VibeZ','Toka'],
    shot: ['Zana ya picha ya skrini haikuweza kuanza.','Hakuna chanzo cha skrini kwa onyesho hili.','Hakuna maonyesho yaliyopatikana.','Picha ya skrini imeshindikana','VibeZ haikuweza kutengeneza picha ya skrini.','Chagua picha ya skrini','Buruta juu ya eneo unalotaka kushiriki · Esc = ghairi'],
    dialog: ['Programu ya mezani ya Mistral Vibe','Nakili taarifa za mfumo','Ripoti tatizo','Funga','Tayari una toleo jipya zaidi la VibeZ.','Haikuwezekana kuangalia masasisho.','Sasisho la VibeZ liko tayari','VibeZ {version} iko tayari kusakinishwa.','Anzisha upya na usasishe','Baadaye','Ukaguzi wa masasisho unapatikana kwenye VibeZ iliyosakinishwa.','Hili ni toleo la Flatpak.','Fungua Releases'],
    settings: ['Mipangilio ya VibeZ','Muunganisho wa mezani','Njia ya mkato ya picha ya skrini ya mfumo mzima','Njia ya mkato ya picha ya skrini','Onyesha kitufe cha Picha ya skrini','Anza wakati wa kuingia','Punguza hadi tray','Funga hadi tray','Onyesho','Uongezaji kasi wa maunzi','Backend ya onyesho','Kuza','Lugha ya VibeZ','Masasisho na kivinjari','Angalia masasisho kiotomatiki','Sakinisha masasisho yaliyopakuliwa VibeZ inapofungwa','Fungua viungo vya nje kwenye kivinjari chaguomsingi','Data ya kivinjari','Weka upya data ya kivinjari','Hifadhi mipangilio','Kiotomatiki','Imewashwa','Imezimwa','Mfumo','Inahifadhi…','Imehifadhiwa.','Imehifadhiwa. Anzisha upya VibeZ kutumia mabadiliko yote ya onyesho/lugha.','Imehifadhiwa, lakini njia hiyo ya mkato tayari inatumika.','Inaangalia masasisho…','Ukaguzi wa masasisho umeanza.','Futa data yote ya kivinjari ya VibeZ? Utaondolewa kwenye Mistral Vibe.','Inafuta data ya kivinjari…','Data ya kivinjari imefutwa.','Data ya kivinjari haikufutwa.']
  },
  ha: {
    menu: ['Manna','Kwafa','Yanke','Zaɓi duka','Bincika da Google','Bincika da DuckDuckGo','Buɗe VibeZ','Hoton allo','Saituna','Duba sabuntawa','Game da VibeZ','Fita'],
    shot: ['Ba a iya fara kayan hoton allo ba.','Babu tushen allo don wannan nuni.','Ba a sami nuni ba.','Hoton allo ya gaza','VibeZ bai iya ƙirƙirar hoton allo ba.','Zaɓi hoton allo','Ja kan yankin da kake son rabawa · Esc = soke'],
    dialog: ['Manhajar tebur don Mistral Vibe','Kwafi bayanan tsarin','Rahoto matsala','Rufe','Kana da sabon sigar VibeZ tuni.','Ba a iya duba sabuntawa ba.','Sabuntawar VibeZ ta shirya','VibeZ {version} ya shirya don girkawa.','Sake farawa da sabuntawa','Daga baya','Duba sabuntawa yana samuwa a sigogin VibeZ da aka girka.','Wannan sigar Flatpak ce.','Buɗe Releases'],
    settings: ['Saitunan VibeZ','Haɗin tebur','Gajeriyar hanyar hoton allo ta duniya','Gajeriyar hanyar hoton allo','Nuna maɓallin Hoton allo','Fara lokacin shiga','Rage zuwa tray','Rufe zuwa tray','Nuni','Hanzarta kayan aiki','Backend na nuni','Zuƙowa','Harshen VibeZ','Sabuntawa da burauza','Duba sabuntawa ta atomatik','Girka sabuntawar da aka sauke lokacin rufe VibeZ','Buɗe hanyoyin waje a burauzar tsoho','Bayanan burauza','Sake saita bayanan burauza','Ajiye saituna','Ta atomatik','A kunne','A kashe','Tsari','Ana ajiyewa…','An ajiye.','An ajiye. Sake kunna VibeZ don amfani da duk sauye-sauyen nuni/harshe.','An ajiye, amma ana amfani da wannan gajeriyar hanyar tuni.','Ana duba sabuntawa…','An fara duba sabuntawa.','A goge duk bayanan burauzar VibeZ? Za a fitar da kai daga Mistral Vibe.','Ana goge bayanan burauza…','An goge bayanan burauza.','Ba a goge bayanan burauza ba.']
  },
  am: {
    menu: ['ለጥፍ','ቅዳ','ቁረጥ','ሁሉንም ምረጥ','በGoogle ፈልግ','በDuckDuckGo ፈልግ','VibeZ ክፈት','የማያ ገጽ ፎቶ','ቅንብሮች','ዝማኔ ፈትሽ','ስለ VibeZ','ውጣ'],
    shot: ['የማያ ገጽ ፎቶ መሣሪያውን ማስጀመር አልተቻለም።','ለዚህ ማሳያ የማያ ምንጭ የለም።','ማሳያ አልተገኘም።','የማያ ገጽ ፎቶ አልተሳካም','VibeZ የማያ ገጽ ፎቶ መፍጠር አልቻለም።','የማያ ገጽ ፎቶ ምረጥ','ማጋራት በሚፈልጉት ክፍል ላይ ይጎትቱ · Esc = ሰርዝ'],
    dialog: ['ለMistral Vibe የዴስክቶፕ ደንበኛ','የስርዓት መረጃ ቅዳ','ችግኝ ሪፖርት አድርግ','ዝጋ','አዲሱ የVibeZ ስሪት አስቀድሞ አለዎት።','ዝማኔ መፈተሽ አልተቻለም።','የVibeZ ዝማኔ ዝግጁ ነው','VibeZ {version} ለመጫን ዝግጁ ነው።','እንደገና አስነሳ እና አዘምን','በኋላ','የዝማኔ ፍተሻ በተጫኑ VibeZ ስሪቶች ይገኛል።','ይህ Flatpak ስሪት ነው።','Releases ክፈት'],
    settings: ['የVibeZ ቅንብሮች','የዴስክቶፕ ውህደት','ዓለም አቀፍ የማያ ገጽ ፎቶ አቋራጭ','የማያ ገጽ ፎቶ አቋራጭ','የማያ ገጽ ፎቶ ቁልፍ አሳይ','ሲገቡ ጀምር','ወደ tray አሳንስ','ወደ tray ዝጋ','ማሳያ','የሃርድዌር ፍጥነት','የማሳያ backend','አጉላ','የVibeZ ቋንቋ','ዝማኔዎች እና አሳሽ','ዝማኔዎችን በራስ-ሰር ፈትሽ','VibeZ ሲዘጋ የወረዱ ዝማኔዎችን ጫን','ውጫዊ አገናኞችን በነባሪ አሳሽ ክፈት','የአሳሽ ውሂብ','የአሳሽ ውሂብ ዳግም አስጀምር','ቅንብሮችን አስቀምጥ','ራስ-ሰር','ነቅቷል','ተሰናክሏል','ስርዓት','በማስቀመጥ ላይ…','ተቀምጧል።','ተቀምጧል። ሁሉንም የማሳያ/ቋንቋ ለውጦች ለመተግበር VibeZ እንደገና ያስነሱ።','ተቀምጧል፣ ግን ይህ አቋራጭ አስቀድሞ ጥቅም ላይ ነው።','ዝማኔ በመፈተሽ ላይ…','የዝማኔ ፍተሻ ተጀምሯል።','ሁሉንም የVibeZ አሳሽ ውሂብ ይሰርዙ? ከMistral Vibe ይወጣሉ።','የአሳሽ ውሂብ በመሰረዝ ላይ…','የአሳሽ ውሂብ ተሰርዟል።','የአሳሽ ውሂብ አልተሰረዘም።']
  },
  jv: {
    menu: ['Tempel','Salin','Potong','Pilih kabeh','Goleki nganggo Google','Goleki nganggo DuckDuckGo','Bukak VibeZ','Tangkapan layar','Setelan','Priksa nganyari','Babagan VibeZ','Metu'],
    shot: ['Piranti tangkapan layar ora bisa diwiwiti.','Ora ana sumber layar kanggo tampilan iki.','Ora ana tampilan sing ditemokake.','Tangkapan layar gagal','VibeZ ora bisa nggawe tangkapan layar.','Pilih tangkapan layar','Seret ing area sing arep dienggo bareng · Esc = batal'],
    dialog: ['Klien desktop kanggo Mistral Vibe','Salin informasi sistem','Lapor masalah','Tutup','Sampeyan wis nggunakake versi VibeZ paling anyar.','Ora bisa mriksa nganyari.','Nganyari VibeZ wis siap','VibeZ {version} siap dipasang.','Wiwiti maneh lan nganyari','Mengko','Priksa nganyari kasedhiya ing VibeZ sing wis dipasang.','Iki versi Flatpak.','Bukak Releases'],
    settings: ['Setelan VibeZ','Integrasi desktop','Trabasan tangkapan layar global','Trabasan tangkapan layar','Tampilake tombol Tangkapan layar','Miwiti nalika mlebu','Nyilikake menyang tray','Tutup menyang tray','Tampilan','Akselerasi hardware','Backend tampilan','Zoom','Basa VibeZ','Nganyari lan browser','Priksa nganyari kanthi otomatis','Pasang nganyari sing wis diundhuh nalika VibeZ ditutup','Bukak pranala njaba ing browser standar','Data browser','Reset data browser','Simpen setelan','Otomatis','Aktif','Ora aktif','Sistem','Nyimpen…','Wis disimpen.','Wis disimpen. Wiwiti maneh VibeZ kanggo ngetrapake kabeh owah-owahan tampilan/basa.','Wis disimpen, nanging trabasan global kasebut wis digunakake.','Priksa nganyari…','Priksa nganyari wis diwiwiti.','Busak kabeh data browser VibeZ? Sampeyan bakal metu saka Mistral Vibe.','Mbusak data browser…','Data browser wis dibusak.','Data browser ora dibusak.']
  }
};
