module.exports = {
  en: {
    menu: ['Paste','Copy','Cut','Select All','Search with Google','Search with DuckDuckGo','Open VibeZ','Screenshot','Settings','Check for updates','About VibeZ','Quit'],
    shot: ['Could not start the screenshot tool.','No screen source is available for this display.','No displays found.','Screenshot failed','VibeZ could not create a screenshot.','Select screenshot','Drag over the area you want to share · Esc = cancel'],
    dialog: ['Desktop client for Mistral Vibe','Copy system information','Report a problem','Close','You already have the latest VibeZ version.','Could not check for updates.','VibeZ update ready','VibeZ {version} is ready to install.','Restart & update','Later','Update checks are available in installed VibeZ builds.','This is the Flatpak build.','Open Releases'],
    settings: ['VibeZ Settings','Desktop integration','Global screenshot shortcut','Screenshot shortcut','Show Screenshot button','Start at login','Minimize to tray','Close to tray','Display','Hardware acceleration','Display backend','Zoom','VibeZ language','Updates & browser','Check for updates automatically','Install downloaded updates when VibeZ closes','Open external links in your default browser','Browser data','Reset browser data','Save settings','Automatic','Enabled','Disabled','System','Saving…','Saved.','Saved. Restart VibeZ to apply all display/language changes.','Saved, but that global shortcut is already in use.','Checking for updates…','Update check started.','Clear all VibeZ browser data? You will be signed out of Mistral Vibe.','Clearing browser data…','Browser data cleared.','Browser data was not cleared.']
  },
  nl: {
    menu: ['Plakken','Kopiëren','Knippen','Alles selecteren','Zoeken met Google','Zoeken met DuckDuckGo','VibeZ openen','Screenshot','Instellingen','Controleren op updates','Over VibeZ','Afsluiten'],
    shot: ['Kon het screenshotgereedschap niet starten.','Geen schermbron beschikbaar voor dit beeldscherm.','Geen beeldschermen gevonden.','Screenshot mislukt','VibeZ kon geen screenshot maken.','Screenshot selecteren','Sleep over het gebied dat je wilt delen · Esc = annuleren'],
    dialog: ['Desktopclient voor Mistral Vibe','Systeeminformatie kopiëren','Probleem melden','Sluiten','Je hebt al de nieuwste versie van VibeZ.','Kon niet controleren op updates.','VibeZ-update gereed','VibeZ {version} is klaar om te installeren.','Herstarten & bijwerken','Later','Updatecontrole is beschikbaar in geïnstalleerde VibeZ-versies.','Dit is de Flatpak-versie.','Releases openen'],
    settings: ['VibeZ-instellingen','Desktopintegratie','Globale screenshot-sneltoets','Screenshot-sneltoets','Screenshotknop tonen','Starten bij aanmelden','Minimaliseren naar systeemvak','Sluiten naar systeemvak','Weergave','Hardwareversnelling','Weergavebackend','Zoom','VibeZ-taal','Updates & browser','Automatisch controleren op updates','Gedownloade updates installeren bij afsluiten','Externe links openen in standaardbrowser','Browsergegevens','Browsergegevens wissen','Instellingen opslaan','Automatisch','Ingeschakeld','Uitgeschakeld','Systeem','Opslaan…','Opgeslagen.','Opgeslagen. Herstart VibeZ om alle weergave-/taalwijzigingen toe te passen.','Opgeslagen, maar die globale sneltoets is al in gebruik.','Controleren op updates…','Updatecontrole gestart.','Alle VibeZ-browsergegevens wissen? Je wordt afgemeld bij Mistral Vibe.','Browsergegevens wissen…','Browsergegevens gewist.','Browsergegevens zijn niet gewist.']
  },
  de: {
    menu: ['Einfügen','Kopieren','Ausschneiden','Alles auswählen','Mit Google suchen','Mit DuckDuckGo suchen','VibeZ öffnen','Screenshot','Einstellungen','Nach Updates suchen','Über VibeZ','Beenden'],
    shot: ['Das Screenshot-Werkzeug konnte nicht gestartet werden.','Für diesen Bildschirm ist keine Bildschirmquelle verfügbar.','Keine Bildschirme gefunden.','Screenshot fehlgeschlagen','VibeZ konnte keinen Screenshot erstellen.','Screenshot auswählen','Über den gewünschten Bereich ziehen · Esc = Abbrechen'],
    dialog: ['Desktop-Client für Mistral Vibe','Systeminformationen kopieren','Problem melden','Schließen','Sie haben bereits die neueste VibeZ-Version.','Updates konnten nicht geprüft werden.','VibeZ-Update bereit','VibeZ {version} kann installiert werden.','Neu starten & aktualisieren','Später','Updateprüfungen sind in installierten VibeZ-Versionen verfügbar.','Dies ist die Flatpak-Version.','Releases öffnen'],
    settings: ['VibeZ-Einstellungen','Desktop-Integration','Globale Screenshot-Tastenkombination','Screenshot-Tastenkombination','Screenshot-Schaltfläche anzeigen','Beim Anmelden starten','In Taskleiste minimieren','In Taskleiste schließen','Anzeige','Hardwarebeschleunigung','Anzeigebackend','Zoom','VibeZ-Sprache','Updates & Browser','Automatisch nach Updates suchen','Geladene Updates beim Beenden installieren','Externe Links im Standardbrowser öffnen','Browserdaten','Browserdaten zurücksetzen','Einstellungen speichern','Automatisch','Aktiviert','Deaktiviert','System','Speichern…','Gespeichert.','Gespeichert. Starten Sie VibeZ neu, um alle Anzeige-/Sprachänderungen anzuwenden.','Gespeichert, aber diese globale Tastenkombination wird bereits verwendet.','Suche nach Updates…','Updateprüfung gestartet.','Alle VibeZ-Browserdaten löschen? Sie werden von Mistral Vibe abgemeldet.','Browserdaten werden gelöscht…','Browserdaten gelöscht.','Browserdaten wurden nicht gelöscht.']
  },
  fr: {
    menu: ['Coller','Copier','Couper','Tout sélectionner','Rechercher avec Google','Rechercher avec DuckDuckGo','Ouvrir VibeZ','Capture','Paramètres','Rechercher des mises à jour','À propos de VibeZ','Quitter'],
    shot: ['Impossible de lancer l’outil de capture.','Aucune source d’écran disponible pour cet écran.','Aucun écran trouvé.','Échec de la capture','VibeZ n’a pas pu créer de capture.','Sélectionner une capture','Faites glisser sur la zone à partager · Échap = annuler'],
    dialog: ['Client de bureau pour Mistral Vibe','Copier les informations système','Signaler un problème','Fermer','Vous avez déjà la dernière version de VibeZ.','Impossible de rechercher des mises à jour.','Mise à jour VibeZ prête','VibeZ {version} est prêt à être installé.','Redémarrer et mettre à jour','Plus tard','La recherche de mises à jour est disponible dans les versions installées.','Ceci est la version Flatpak.','Ouvrir Releases'],
    settings: ['Paramètres VibeZ','Intégration bureau','Raccourci global de capture','Raccourci de capture','Afficher le bouton Capture','Démarrer à la connexion','Réduire dans la zone de notification','Fermer dans la zone de notification','Affichage','Accélération matérielle','Backend d’affichage','Zoom','Langue de VibeZ','Mises à jour & navigateur','Rechercher automatiquement les mises à jour','Installer les mises à jour téléchargées à la fermeture','Ouvrir les liens externes dans le navigateur par défaut','Données du navigateur','Réinitialiser les données du navigateur','Enregistrer','Automatique','Activé','Désactivé','Système','Enregistrement…','Enregistré.','Enregistré. Redémarrez VibeZ pour appliquer tous les changements d’affichage/langue.','Enregistré, mais ce raccourci global est déjà utilisé.','Recherche de mises à jour…','Recherche de mise à jour lancée.','Effacer toutes les données navigateur de VibeZ ? Vous serez déconnecté de Mistral Vibe.','Effacement des données…','Données du navigateur effacées.','Les données du navigateur n’ont pas été effacées.']
  },
  es: {
    menu: ['Pegar','Copiar','Cortar','Seleccionar todo','Buscar con Google','Buscar con DuckDuckGo','Abrir VibeZ','Captura','Ajustes','Buscar actualizaciones','Acerca de VibeZ','Salir'],
    shot: ['No se pudo iniciar la herramienta de captura.','No hay una fuente de pantalla disponible para este monitor.','No se encontraron pantallas.','Error de captura','VibeZ no pudo crear una captura.','Seleccionar captura','Arrastra sobre el área que quieres compartir · Esc = cancelar'],
    dialog: ['Cliente de escritorio para Mistral Vibe','Copiar información del sistema','Informar de un problema','Cerrar','Ya tienes la última versión de VibeZ.','No se pudo buscar actualizaciones.','Actualización de VibeZ lista','VibeZ {version} está listo para instalar.','Reiniciar y actualizar','Más tarde','La búsqueda de actualizaciones está disponible en versiones instaladas.','Esta es la versión Flatpak.','Abrir Releases'],
    settings: ['Ajustes de VibeZ','Integración de escritorio','Atajo global de captura','Atajo de captura','Mostrar botón Captura','Iniciar al entrar','Minimizar a la bandeja','Cerrar a la bandeja','Pantalla','Aceleración por hardware','Backend de pantalla','Zoom','Idioma de VibeZ','Actualizaciones y navegador','Buscar actualizaciones automáticamente','Instalar actualizaciones descargadas al cerrar','Abrir enlaces externos en el navegador predeterminado','Datos del navegador','Restablecer datos del navegador','Guardar ajustes','Automático','Activado','Desactivado','Sistema','Guardando…','Guardado.','Guardado. Reinicia VibeZ para aplicar todos los cambios de pantalla/idioma.','Guardado, pero ese atajo global ya está en uso.','Buscando actualizaciones…','Búsqueda de actualización iniciada.','¿Borrar todos los datos del navegador de VibeZ? Se cerrará tu sesión de Mistral Vibe.','Borrando datos…','Datos del navegador borrados.','Los datos del navegador no se borraron.']
  },
  it: {
    menu: ['Incolla','Copia','Taglia','Seleziona tutto','Cerca con Google','Cerca con DuckDuckGo','Apri VibeZ','Schermata','Impostazioni','Controlla aggiornamenti','Informazioni su VibeZ','Esci'],
    shot: ['Impossibile avviare lo strumento di cattura.','Nessuna sorgente schermo disponibile per questo monitor.','Nessuno schermo trovato.','Cattura non riuscita','VibeZ non è riuscito a creare una schermata.','Seleziona schermata','Trascina sull’area da condividere · Esc = annulla'],
    dialog: ['Client desktop per Mistral Vibe','Copia informazioni di sistema','Segnala un problema','Chiudi','Hai già l’ultima versione di VibeZ.','Impossibile controllare gli aggiornamenti.','Aggiornamento VibeZ pronto','VibeZ {version} è pronto per l’installazione.','Riavvia e aggiorna','Più tardi','Il controllo aggiornamenti è disponibile nelle versioni installate.','Questa è la versione Flatpak.','Apri Releases'],
    settings: ['Impostazioni VibeZ','Integrazione desktop','Scorciatoia globale schermata','Scorciatoia schermata','Mostra pulsante Schermata','Avvia all’accesso','Riduci nell’area di notifica','Chiudi nell’area di notifica','Display','Accelerazione hardware','Backend display','Zoom','Lingua VibeZ','Aggiornamenti e browser','Controlla automaticamente gli aggiornamenti','Installa gli aggiornamenti scaricati alla chiusura','Apri link esterni nel browser predefinito','Dati browser','Reimposta dati browser','Salva impostazioni','Automatico','Attivato','Disattivato','Sistema','Salvataggio…','Salvato.','Salvato. Riavvia VibeZ per applicare tutte le modifiche display/lingua.','Salvato, ma quella scorciatoia globale è già in uso.','Controllo aggiornamenti…','Controllo aggiornamenti avviato.','Cancellare tutti i dati browser di VibeZ? Verrai disconnesso da Mistral Vibe.','Cancellazione dati…','Dati browser cancellati.','I dati browser non sono stati cancellati.']
  },
  pt: {
    menu: ['Colar','Copiar','Cortar','Selecionar tudo','Pesquisar com Google','Pesquisar com DuckDuckGo','Abrir VibeZ','Captura','Definições','Procurar atualizações','Sobre o VibeZ','Sair'],
    shot: ['Não foi possível iniciar a ferramenta de captura.','Não há uma fonte de ecrã disponível para este monitor.','Não foram encontrados ecrãs.','Falha na captura','O VibeZ não conseguiu criar uma captura.','Selecionar captura','Arraste sobre a área a partilhar · Esc = cancelar'],
    dialog: ['Cliente de ambiente de trabalho para Mistral Vibe','Copiar informações do sistema','Reportar um problema','Fechar','Já tem a versão mais recente do VibeZ.','Não foi possível procurar atualizações.','Atualização do VibeZ pronta','O VibeZ {version} está pronto para instalar.','Reiniciar e atualizar','Mais tarde','A procura de atualizações está disponível em versões instaladas.','Esta é a versão Flatpak.','Abrir Releases'],
    settings: ['Definições do VibeZ','Integração de desktop','Atalho global de captura','Atalho de captura','Mostrar botão Captura','Iniciar ao entrar','Minimizar para a área de notificação','Fechar para a área de notificação','Ecrã','Aceleração por hardware','Backend de ecrã','Zoom','Idioma do VibeZ','Atualizações e navegador','Procurar atualizações automaticamente','Instalar atualizações descarregadas ao fechar','Abrir links externos no navegador predefinido','Dados do navegador','Repor dados do navegador','Guardar definições','Automático','Ativado','Desativado','Sistema','A guardar…','Guardado.','Guardado. Reinicie o VibeZ para aplicar todas as alterações de ecrã/idioma.','Guardado, mas esse atalho global já está em uso.','A procurar atualizações…','Procura de atualização iniciada.','Limpar todos os dados do navegador do VibeZ? A sessão no Mistral Vibe será terminada.','A limpar dados…','Dados do navegador limpos.','Os dados do navegador não foram limpos.']
  }
};
